### ISSUE TITLE
Component does not work when building the frontend

### ISSUE THREAD

**Issue by murilo-cunha** [whitphx/streamlit-component-template-react-hooks#90]
Hi @whitphx, long time no speak 🖖 

I really enjoy the react hooks-based approach, but I'm getting an error when I build the frontend and declare the component...

<img width="704" alt="image" src="https://user-images.githubusercontent.com/44590097/204151690-51fe4386-ce86-49db-b861-dd72764bac7d.png">

I don't think the issue is with the react-hooks template, but also running out of ideas.. For development - that is, when I manually run `yarn start` on the `frontend/` directory and have `_RELEASE=False` everything works as expected.

After some research, it looks like it's a timeout thing on the [Typescript side](https://github.com/streamlit/streamlit/blob/9d4472272bcc57eb6a6662f476a0a53ba657d074/frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx).

Related links:
- https://discuss.streamlit.io/t/any-ideas-on-your-app-is-having-trouble-loading-the-st-aggrid-aggrid-component/10176/19
- https://discuss.streamlit.io/t/any-ideas-on-your-app-is-having-trouble-loading-the-st-aggrid-aggrid-component/10176/23
- My repo: https://github.com/murilo-cunha/stream-wars

**Comment by whitphx** [comment]
Hi,

I could not reproduce the problem with [your repo](https://github.com/murilo-cunha/stream-wars).

### What I did
```shell
git clone https://github.com/murilo-cunha/stream-wars.git
cd stream-wars
poetry install
```

Edit the code
```diff
index 72f329e..61e1178 100644
--- a/stream_wars/__init__.py
+++ b/stream_wars/__init__.py
 if Path(".streamlit/secrets.toml").is_file():
     _RELEASE = st.secrets.get("STREAMLIT_RELEASE", True)
 else:
-    _RELEASE = True
+    _RELEASE = False
```

Comment out the lines in `stream_wars/docs.py`

Set up the frontend
```shell
cd stream_wars/frontend
yarn
yarn start
```

Run the app
```
poetry shell
streamlit run stream_wars/docs.py
```

**Comment by whitphx** [comment]
[`"homepage": "."`](https://github.com/whitphx/streamlit-component-template-react-hooks/blob/cbee49d0bcbe7e3e2d0e7bb85de12d46e721d472/template/my_component/frontend/package.json#L40) has been removed in your `frontend/package.json`.
Revert it.

**Comment by whitphx** [comment]
That specification is used to build the JS and CSS files to be linked through relative paths from the `index.html` with the [CRA setting](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths).

If you want to change or remove the `"homepage"` field, use the [`PUBLIC_PATH` envvar](https://create-react-app.dev/docs/advanced-configuration/) with the build command.

**Comment by murilo-cunha** [comment]
That worked like a charm! Thank you so much!! 🙏 🙏 🙏 

#StreamlitWiz 🧙‍♂️
